name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: |
        go build main.go
    - name: Run
      run: |
        mkdir ${{ runner.temp }}/build_logs
        ./main --log-path ${{ runner.temp }}/build_logs

    - name: Echo
      run: |
        cd ${{ runner.temp }}/build_logs
        ls
      if: ${{ failure() }}

    - name: Read package.json
      if: ${{ failure() }}
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: main.go
    - name: Echo main.go
      if: ${{ failure() }}
      run: echo "${{ steps.package.outputs.content }}"
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() }}
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: xuzhiqing2014@outlook.com,xuzhiqing2014@163.com
        from: Josiah # <user@example.com>
        secure: true
        body: Build job of ${{github.repository}} completed successfully!

