name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: |
        go build main.go

    - name: Run
      run: |
        ./main > detail.log

    - name: Make summary log
      if: ${{ failure() }}
      run: |
        tail -1 detail.log > summary.log

    - name: Read lastest log
      if: ${{ failure() }}
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: summary.txt
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() }}
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Databend Pert Actions job result
        to: xuzhiqing2014@outlook.com, xuzhiqing2014@163.com
        from: databend-perf
        secure: true
        body: "Build job of ${{github.repository}} perf-tool run failed, lastest output: \n${{ steps.package.outputs.content }}. \n For detail log, see attachment file."
        attachments: detail.log

