name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run
      run: go run main.go

    - name: Echo
      run: echo aaaaaaa
      if: ${{ failure() }}
    
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      if: ${{ failure() }}
      with:
        server_address: smtp.feishu.cn
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Github Actions job result
        to: xuzhiqing2014@outlook.com,xuzhiqing2014@163.com
        from: Josiah # <user@example.com>
        secure: true
        body: Build job of ${{github.repository}} completed successfully!

