# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: create public
        run:
          mkdir public
     
      - name: show go version
        run: go version

      - name: run go programe
        run: go run main.go

      - name: build file
        run: touch public/deff.txt

      - name: build file2
        run: 
          mkdir public/abcdd
          touch public/abcdd/def.txt

      - name: deploy
      - uses: manzoorwanijk/action-deploy-to-repo@master
        with: 
          src_dir: public
          target_dir: public/json
          target_owner: zqxul
          target_repo: pages
          target_branch: gh-pages
